import discord

class topics():
    standard = [
    	"What did you do yesterday?",
    	"What's your favourite movie?",
    	"What's your favourite book?",
    	"What's the worst thing you've ever done?",
    	"What's the word that best describes you?",
    	"What's the dumbest thing you've ever done?",
    	"What's your favourite video game?",
    	"What's something more people should know about?",
    	"What's the nicest thing you've ever done?",
    	"What's the dumbest thing you've ever bought?",
    	"What's a video game that needs more attention?",
    	"If you had one with, what would you use it on?",
    	"What's your dream job?",
    	"What do you do to waste time?",
    	"What's on your clipboard?",
	]
    link = [
    	'https://youtu.be/_C0fxoot-7c',
    	'https://youtu.be/JYYqsvsD_Sk',
    	'https://youtu.be/U06jlgpMtQs',
    	'https://youtu.be/lmIlogViPes',
    	'https://youtu.be/kjYp7_mzuJs',
    	'https://youtu.be/HCdn0zg6NDM',
    	'https://youtu.be/3aATuQAMG-k',
    	'https://youtu.be/e4nc3uO_eCQ',
    	'https://youtu.be/u-ILeS3wH2c',
    	'https://youtu.be/_MBgz9h7GGM',
    	'https://youtu.be/SVdQxZX4De8',
    	'https://youtu.be/mpej9Mwz3MA?t=73',
    	'https://tinyurl.com/7uonyyu',
    	'https://tinyurl.com/y2pd442v',
    	'https://tinyurl.com/yy7ly2gy',
    	'https://tinyurl.com/y4dxr7r3',
    	'https://tinyurl.com/y26ezznx',
    	'https://tinyurl.com/y6c59ccp',
    	'https://tinyurl.com/y63c8urr',
    	'https://tinyurl.com/y3zbq45e',
    	'https://tinyurl.com/y4psmh98',
    	'https://tinyurl.com/yy4m77ua',
    	'https://tinyurl.com/y2eowogy',
    	'https://tinyurl.com/y62nyrg6',
    	'https://tinyurl.com/y33ulmek',
    	'https://tinyurl.com/yy54msab',
    	'https://tinyurl.com/yxlvl7wy',
    	'https://tinyurl.com/y2dmruxj',
    	'https://tinyurl.com/y5z3qlmz',
    	'https://tinyurl.com/yxdjzbpr',
    	'https://tinyurl.com/y544n7u8',
    	'https://tinyurl.com/y5ddkt9o',
    	'https://tinyurl.com/y55fxwxo',
    	'https://tinyurl.com/y26b4ghp',
    	'https://tinyurl.com/y2pu6kn7',
    	'https://tinyurl.com/y5ek4pwd',
    	'https://tinyurl.com/y35ogmbw',
    	'https://tinyurl.com/dymbb3a',
    	'https://tinyurl.com/yyuvxlge',
    	'https://tinyurl.com/y556eyuk',
    	'https://tinyurl.com/y5zqjk8h',
    	'https://tinyurl.com/y6zqfhkb',
    	'https://tinyurl.com/yxwt68jj',
    	'https://tinyurl.com/y227ssc2',
    	'https://tinyurl.com/yxrldlt2',
    	'https://tinyurl.com/y3y77ozl',
    	'https://tinyurl.com/y37g4edo',
    	'https://tinyurl.com/yyynd3mz',
    	'https://tinyurl.com/y4oqa3ex',
    	'https://tinyurl.com/yy4q686u',
    	'https://tinyurl.com/y5t4dt9o',
    	'https://tinyurl.com/ycdcvf3b',
    	'https://tinyurl.com/yy4pvvg5',
    	'https://tinyurl.com/y3c5owx5',
    	'https://tinyurl.com/y6kutvbz',
    	'https://tinyurl.com/y6ezbtkf',
    	'https://tinyurl.com/y57kudsa',
    	'https://tinyurl.com/yy3og3z8',
    	'https://tinyurl.com/y2kyefx5',
    	'https://tinyurl.com/y5o7t66c',
    	'https://tinyurl.com/y3xj7skc',
    	'https://tinyurl.com/y6edna4j',
    	'https://tinyurl.com/y37sym7l',
    	'https://tinyurl.com/y6edom9y',
    	'https://tinyurl.com/yy22abgf',
    	'https://tinyurl.com/y29tqt5l',
    	'https://tinyurl.com/y4dz8hvu',
    	'https://tinyurl.com/y4hzx3ye',
    	'https://tinyurl.com/y4ubl8hu',
    	'https://tinyurl.com/y6yfxo74',
    	'https://tinyurl.com/y3759b2k',
    	'https://tinyurl.com/y4258hc9',
    	'https://tinyurl.com/yxshbj4a',
    	'https://tinyurl.com/y5nxu8xn',
    	'https://tinyurl.com/y4pcobnm',
    	'https://tinyurl.com/y5uzn89s',
    	'https://tinyurl.com/y2v3pyrx',
    	'https://tinyurl.com/yxesa23w',
    	'https://tinyurl.com/yyopz6mp',
    	'https://tinyurl.com/y3e6urqf',
    	'https://tinyurl.com/y5e9b756',
    	'https://tinyurl.com/yxmmncnj',
    	'https://tinyurl.com/y63vqhrb',
    	'https://tinyurl.com/y2a4ra8s',
    	'https://tinyurl.com/y4fuzlxy',
    	'https://tinyurl.com/y3hv9m7x',
    	'https://tinyurl.com/yxh99b83',
    	'https://tinyurl.com/y42kag23',
    	'https://tinyurl.com/y2fkrlem',
    	'https://tinyurl.com/y24cc5k2',
    	'https://tinyurl.com/y6jr8vbj',
    	'https://tinyurl.com/y4nw2ac6',
    	]

topicTypes = {
    "": topics.standard,
    "link": topics.link,
}


colours = {
    "teal": discord.Colour.teal,
    "dark_teal": discord.Colour.dark_teal,
    "green": discord.Colour.green,
    "dark_green": discord.Colour.dark_green,
    "blue": discord.Colour.blue,
    "dark_blue": discord.Colour.dark_blue,
    "purple": discord.Colour.purple,
    "dark_purple": discord.Colour.dark_purple,
    "magenta": discord.Colour.magenta,
    "dark_magenta": discord.Colour.dark_magenta,
    "gold": discord.Colour.gold,
    "dark_gold": discord.Colour.dark_gold,
    "orange": discord.Colour.orange,
    "dark_orange": discord.Colour.dark_orange,
    "red": discord.Colour.red,
    "dark_red": discord.Colour.dark_red,
    "lighter_grey": discord.Colour.lighter_grey,
    "dark_grey": discord.Colour.dark_grey,
    "light_grey": discord.Colour.light_grey,
    "darker_grey": discord.Colour.darker_grey,
    "blurple": discord.Colour.blurple,
    "greyple": discord.Colour.greyple,
    }

def colour(colour):
    if colour in colours:
        for i in colours:
            if i == colour:
                return colours[i]()
                break
    else:
        return colours["blurple"]()
